version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: stylelint-config-recommended
    versions:
    - 4.0.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.6
  - dependency-name: sass-loader
    versions:
    - 11.0.0
